name: CI-CD

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  TF_DIR: ./infra/envs/dev
  APP_IMAGE_NAME: techflow-api
  JOB_IMAGE_NAME: techflow-job

jobs:
  build-security-deploy:
    runs-on: ubuntu-latest


    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login a Azure desde el inicio (backend azurerm con use_azuread_auth=true lo necesita)
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -------------------------
      # Terraform fmt/init/validate (+plan en PR)
      # -------------------------
      - name: Terraform fmt
        working-directory: ${{ env.TF_DIR }}
        run: terraform fmt -check -recursive

      - name: Terraform init (remote state using Azure AD)
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ vars.TFSTATE_RG }}" \
            -backend-config="storage_account_name=${{ vars.TFSTATE_STORAGE }}" \
            -backend-config="container_name=${{ vars.TFSTATE_CONTAINER }}" \
            -backend-config="key=${{ github.ref_name }}.tfstate" \
            -backend-config="use_azuread_auth=true"

      - name: Terraform validate
        working-directory: ${{ env.TF_DIR }}
        run: terraform validate

      - name: Terraform plan (solo PR, sin deploy)
        if: github.event_name == 'pull_request'
        working-directory: ${{ env.TF_DIR }}
        run: terraform plan -no-color

      # -------------------------
      # Checkov -> SARIF (no rompe deploy)
      # -------------------------
      - name: IaC scan (Checkov)
        continue-on-error: true
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ env.TF_DIR }}
          quiet: true
          output_format: sarif
          output_file_path: ${{ github.workspace }}/checkov.sarif
          skip_check: "CKV_AZURE_166,CKV_AZURE_139,CKV_AZURE_233,CKV_AZURE_163,CKV_AZURE_167,CKV_AZURE_164,CKV_AZURE_237,CKV_AZURE_165,CKV_AZURE_189,CKV_AZURE_109,CKV2_AZURE_32"

      - name: Upload Checkov SARIF
        if: always()
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/checkov.sarif

      # -------------------------
      # Docker build (si falla, SI debe frenar deploy)
      # -------------------------
      - name: Docker build (api)
        run: docker build -t $APP_IMAGE_NAME:${{ github.sha }} ./app

      - name: Docker build (job)
        run: docker build -t $JOB_IMAGE_NAME:${{ github.sha }} ./job

      # -------------------------
      # Trivy -> SARIF (no bloquea, solo evidencia)
      # -------------------------
      - name: Trivy scan (api image) - SARIF report
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.APP_IMAGE_NAME }}:${{ github.sha }}
          scan-type: image
          format: sarif
          output: ${{ github.workspace }}/trivy-api.sarif
          vuln-type: os,library
          severity: CRITICAL,HIGH
          exit-code: "0"

      - name: Upload Trivy SARIF (api)
        if: always()
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/trivy-api.sarif

      - name: Trivy scan (job image) - SARIF report
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.JOB_IMAGE_NAME }}:${{ github.sha }}
          scan-type: image
          format: sarif
          output: ${{ github.workspace }}/trivy-job.sarif
          vuln-type: os,library
          severity: CRITICAL,HIGH
          exit-code: "0"

      - name: Upload Trivy SARIF (job)
        if: always()
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/trivy-job.sarif

      # --------------------------
      # DEPLOY solo en PUSH (no PR)
      # --------------------------
      - name: Guard - ACR_NAME must exist
        if: github.event_name == 'push'
        run: |
          if [ -z "${{ vars.ACR_NAME }}" ]; then
            echo "ERROR: vars.ACR_NAME is empty or not defined in GitHub Actions Variables"
            exit 1
          fi

      - name: ACR login
        if: github.event_name == 'push' && (github.ref_name == 'develop' || github.ref_name == 'main')
        run: az acr login --name "${{ vars.ACR_NAME }}"

      - name: Tag & Push images to ACR
        if: github.event_name == 'push' && (github.ref_name == 'develop' || github.ref_name == 'main')
        run: |
          ACR_LOGIN_SERVER=$(az acr show -n "${{ vars.ACR_NAME }}" --query loginServer -o tsv)

          docker tag $APP_IMAGE_NAME:${{ github.sha }} $ACR_LOGIN_SERVER/$APP_IMAGE_NAME:${{ github.sha }}
          docker push $ACR_LOGIN_SERVER/$APP_IMAGE_NAME:${{ github.sha }}

          docker tag $JOB_IMAGE_NAME:${{ github.sha }} $ACR_LOGIN_SERVER/$JOB_IMAGE_NAME:${{ github.sha }}
          docker push $ACR_LOGIN_SERVER/$JOB_IMAGE_NAME:${{ github.sha }}

      - name: Terraform apply
        if: github.event_name == 'push' && (github.ref_name == 'develop' || github.ref_name == 'main')
        working-directory: ${{ env.TF_DIR }}
        env:
          TF_VAR_app_image_tag: ${{ github.sha }}
          TF_VAR_job_image_tag: ${{ github.sha }}
          TF_VAR_my_secret_value: ${{ secrets.MY_SECRET_VALUE }}
        run: terraform apply -auto-approve
