name: CI-CD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  TF_DIR: ./infra/envs/dev

  
  APP_IMAGE_NAME: techflow-api
  JOB_IMAGE_NAME: techflow-job

jobs:
  build-security-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        working-directory: ${{ env.TF_DIR }}
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform validate
        working-directory: ${{ env.TF_DIR }}
        run: terraform validate


      - name: IaC scan (Checkov)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ env.TF_DIR }}
          quiet: true
          output_format: sarif
          output_file_path: results.sarif
          skip_check: "CKV_AZURE_166,CKV_AZURE_139,CKV_AZURE_233,CKV_AZURE_163,CKV_AZURE_167,CKV_AZURE_164,CKV_AZURE_237,CKV_AZURE_165,CKV_AZURE_189,CKV_AZURE_109,CKV2_AZURE_32"

      - name: Upload Checkov SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif


      - name: Docker build (api)
        run: |
          docker build -t $APP_IMAGE_NAME:${{ github.sha }} ./app

      - name: Docker build (job)
        run: |
          docker build -t $JOB_IMAGE_NAME:${{ github.sha }} ./job


      - name: Trivy scan (api image)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.APP_IMAGE_NAME }}:${{ github.sha }}
          format: table
          vuln-type: os,library
          severity: CRITICAL
          exit-code: 1

      - name: Trivy scan (job image)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.JOB_IMAGE_NAME }}:${{ github.sha }}
          format: table
          vuln-type: os,library
          severity: CRITICAL
          exit-code: 1
                

      # --------------------------
      # SOLO DEPLOY EN PUSH A DEVELOP
      # --------------------------

      - name: Azure Login (OIDC)
        if: github.event_name != 'pull_request'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI - Show account
        if: github.event_name != 'pull_request'
        run: az account show

      - name: ACR login
        if: github.event_name != 'pull_request'
        run: |
          az acr login --name ${{ vars.ACR_NAME }}

      - name: Tag & Push images to ACR
        if: github.event_name != 'pull_request'
        run: |
          ACR_LOGIN_SERVER=$(az acr show -n ${{ vars.ACR_NAME }} --query loginServer -o tsv)

          docker tag $APP_IMAGE_NAME:${{ github.sha }} $ACR_LOGIN_SERVER/$APP_IMAGE_NAME:${{ github.sha }}
          docker push $ACR_LOGIN_SERVER/$APP_IMAGE_NAME:${{ github.sha }}

          docker tag $JOB_IMAGE_NAME:${{ github.sha }} $ACR_LOGIN_SERVER/$JOB_IMAGE_NAME:${{ github.sha }}
          docker push $ACR_LOGIN_SERVER/$JOB_IMAGE_NAME:${{ github.sha }}

      - name: Terraform apply (deploy dev)
        if: github.event_name != 'pull_request'
        working-directory: ${{ env.TF_DIR }}
        env:
          TF_VAR_app_image_tag: ${{ github.sha }}
          TF_VAR_job_image_tag: ${{ github.sha }}
        run: terraform apply -auto-approve
